# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #Boton volver
        self.volver_boton = QtWidgets.QPushButton(self.centralwidget)
        self.volver_boton.setGeometry(QtCore.QRect(0, 5, 71, 30))
        self.volver_boton.setObjectName("volver_boton")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 37, 841, 199))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        #Cuadro de semana
        self.SemanaLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.SemanaLayout.setContentsMargins(0, 0, 0, 0)
        self.SemanaLayout.setObjectName("SemanaLayout")
        
        #Cuadro General
        self.GeneralLayout = QtWidgets.QVBoxLayout()
        self.GeneralLayout.setObjectName("GeneralLayout")
        self.cartel_general = QtWidgets.QLabel(self.horizontalLayoutWidget) #Etiqueta General
        self.cartel_general.setObjectName("cartel_general")
        self.GeneralLayout.addWidget(self.cartel_general)
        #Entrada de limite/dia general
        self.lm_grl = QtWidgets.QSpinBox(self.horizontalLayoutWidget) 
        self.lm_grl.setObjectName("lm_grl")
        self.lm_grl.clear()  
        self.lm_grl.setSpecialValueText("--")
        self.lm_grl.setMinimum(-1)
        self.lm_grl.setMaximum(10)
        self.lm_grl.setValue(-1)
        self.GeneralLayout.addWidget(self.lm_grl)
        #Horario general 1 "general time"
        self.grl_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.grl_tm1.setObjectName("grl_tm1")
        self.grl_tm1.clear()  
        self.grl_tm1.setSpecialValueText("--:--:--")  
        self.grl_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.grl_tm1.setTime(QtCore.QTime())  
        self.GeneralLayout.addWidget(self.grl_tm1)
        #horario general 2 "general time"
        self.grl_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.grl_tm2.setObjectName("grl_tm2")
        self.grl_tm2.clear()  
        self.grl_tm2.setSpecialValueText("--:--:--")  
        self.grl_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.grl_tm2.setTime(QtCore.QTime())  
        self.GeneralLayout.addWidget(self.grl_tm2)
        #Horario general 3 "general time"
        self.grl_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.grl_tm3.setObjectName("grl_tm3")
        self.grl_tm3.clear()  
        self.grl_tm3.setSpecialValueText("--:--:--")  
        self.grl_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.grl_tm3.setTime(QtCore.QTime())  
        self.GeneralLayout.addWidget(self.grl_tm3)
        #Horario general 4 "general time"
        self.grl_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.grl_tm4.setObjectName("grl_tm4")
        self.grl_tm4.clear()  
        self.grl_tm4.setSpecialValueText("--:--:--") 
        self.grl_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.grl_tm4.setTime(QtCore.QTime())  
        self.GeneralLayout.addWidget(self.grl_tm4)
        #Horario general 5 "general time"
        self.grl_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.grl_tm5.setObjectName("grl_tm5")
        self.grl_tm5.clear() 
        self.grl_tm5.setSpecialValueText("--:--:--")  
        self.grl_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.grl_tm5.setTime(QtCore.QTime())  
        self.GeneralLayout.addWidget(self.grl_tm5)
        
        self.SemanaLayout.addLayout(self.GeneralLayout) #añadir cuadro general al cuadro semana

        #Cuadro Lunes
        self.LunesLayout = QtWidgets.QVBoxLayout()
        self.LunesLayout.setObjectName("LunesLayout")
        self.cartel_lunes = QtWidgets.QLabel(self.horizontalLayoutWidget) #Etiqueta lunes
        self.cartel_lunes.setObjectName("cartel_lunes")
        self.LunesLayout.addWidget(self.cartel_lunes)
        #Entrada de limite de lunes 
        self.lm_lu = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_lu.setObjectName("lm_lu")
        self.lm_lu.clear()  
        self.lm_lu.setSpecialValueText("--")
        self.lm_lu.setMinimum(-1)
        self.lm_lu.setMaximum(10)
        self.lm_lu.setValue(-1)
        self.LunesLayout.addWidget(self.lm_lu)
        #Horario lunes 1
        self.lu_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.lu_tm1.setObjectName("lu_tm1")
        self.lu_tm1.clear()  
        self.lu_tm1.setSpecialValueText("--:--:--")  
        self.lu_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.lu_tm1.setTime(QtCore.QTime())  
        self.LunesLayout.addWidget(self.lu_tm1)
        #Horario lunes 2
        self.lu_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.lu_tm2.setObjectName("lu_tm2")
        self.lu_tm2.clear()  
        self.lu_tm2.setSpecialValueText("--:--:--")  
        self.lu_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.lu_tm2.setTime(QtCore.QTime()) 
        self.LunesLayout.addWidget(self.lu_tm2)
        #Horario lunes 3
        self.lu_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.lu_tm3.setObjectName("lu_tm3")
        self.lu_tm3.clear()  
        self.lu_tm3.setSpecialValueText("--:--:--")  
        self.lu_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.lu_tm3.setTime(QtCore.QTime())  
        self.LunesLayout.addWidget(self.lu_tm3)
        #Horario lunes 4
        self.lu_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.lu_tm4.setObjectName("lu_tm4")
        self.lu_tm4.clear()  
        self.lu_tm4.setSpecialValueText("--:--:--") 
        self.lu_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.lu_tm4.setTime(QtCore.QTime())  
        self.LunesLayout.addWidget(self.lu_tm4)
        #Horario lunes 5
        self.lu_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.lu_tm5.setObjectName("lu_tm5")
        self.lu_tm5.clear()  
        self.lu_tm5.setSpecialValueText("--:--:--")  
        self.lu_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.lu_tm5.setTime(QtCore.QTime())  
        self.LunesLayout.addWidget(self.lu_tm5)
       
        self.SemanaLayout.addLayout(self.LunesLayout) #añade cuadro lunes al cuadro semana

        #Cuadro Martes
        self.MartesLayout = QtWidgets.QVBoxLayout()
        self.MartesLayout.setObjectName("MartesLayout")       
        self.cartel_martes = QtWidgets.QLabel(self.horizontalLayoutWidget) #etiqueta martes
        self.cartel_martes.setObjectName("cartel_martes")
        self.MartesLayout.addWidget(self.cartel_martes)
        #Entrada limite martes
        self.lm_mt = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_mt.setObjectName("lm_mt")
        self.lm_mt.clear()  
        self.lm_mt.setSpecialValueText("--")
        self.lm_mt.setMinimum(-1)
        self.lm_mt.setMaximum(10)
        self.lm_mt.setValue(-1)
        self.MartesLayout.addWidget(self.lm_mt)
        #Horario martes 1
        self.mt_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mt_tm1.setObjectName("mt_tm1")
        self.mt_tm1.clear() 
        self.mt_tm1.setSpecialValueText("--:--:--")  
        self.mt_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mt_tm1.setTime(QtCore.QTime())  
        self.MartesLayout.addWidget(self.mt_tm1)
        #Horario martes 2
        self.mt_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mt_tm2.setObjectName("mt_tm2")
        self.mt_tm2.clear()  
        self.mt_tm2.setSpecialValueText("--:--:--")  
        self.mt_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mt_tm2.setTime(QtCore.QTime())  
        self.MartesLayout.addWidget(self.mt_tm2)
        #Horario martes 3
        self.mt_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mt_tm3.setObjectName("mt_tm3")
        self.mt_tm3.clear()  
        self.mt_tm3.setSpecialValueText("--:--:--")  
        self.mt_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mt_tm3.setTime(QtCore.QTime())  
        self.MartesLayout.addWidget(self.mt_tm3)
        #Horario martes 4
        self.mt_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mt_tm4.setObjectName("mt_tm4")
        self.mt_tm4.clear()  
        self.mt_tm4.setSpecialValueText("--:--:--")  
        self.mt_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mt_tm4.setTime(QtCore.QTime())  
        self.MartesLayout.addWidget(self.mt_tm4)
        #Horario martes 5
        self.mt_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mt_tm5.setObjectName("mt_tm5")
        self.mt_tm5.clear() 
        self.mt_tm5.setSpecialValueText("--:--:--")  
        self.mt_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mt_tm5.setTime(QtCore.QTime())  
        self.MartesLayout.addWidget(self.mt_tm5)
        
        self.SemanaLayout.addLayout(self.MartesLayout) #añade cuadro martes al cuadro semana
        
        #Cuadro Miercoles
        self.MiercolesLayout = QtWidgets.QVBoxLayout()
        self.MiercolesLayout.setObjectName("MiercolesLayout")
        self.cartel_miercoles = QtWidgets.QLabel(self.horizontalLayoutWidget) #etiqueta miercoles
        self.cartel_miercoles.setObjectName("cartel_miercoles")
        self.MiercolesLayout.addWidget(self.cartel_miercoles)
        #entrada limite miercoles
        self.lm_mc = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_mc.setObjectName("lm_mc")
        self.lm_mc.clear()  
        self.lm_mc.setSpecialValueText("--")
        self.lm_mc.setMinimum(-1)
        self.lm_mc.setMaximum(10)
        self.lm_mc.setValue(-1)
        self.MiercolesLayout.addWidget(self.lm_mc)
        #Horario miercoles 1
        self.mc_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mc_tm1.setObjectName("mc_tm1")
        self.mc_tm1.clear()  
        self.mc_tm1.setSpecialValueText("--:--:--")  
        self.mc_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mc_tm1.setTime(QtCore.QTime())  
        self.MiercolesLayout.addWidget(self.mc_tm1)
        #Horario miercoles 2
        self.mc_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mc_tm2.setObjectName("mc_tm2")
        self.mc_tm2.clear()  
        self.mc_tm2.setSpecialValueText("--:--:--")  
        self.mc_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mc_tm2.setTime(QtCore.QTime())  
        self.MiercolesLayout.addWidget(self.mc_tm2)
        #Horario miercoles 3
        self.mc_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mc_tm3.setObjectName("mc_tm3")
        self.mc_tm3.clear()  
        self.mc_tm3.setSpecialValueText("--:--:--")  
        self.mc_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mc_tm3.setTime(QtCore.QTime()) 
        self.MiercolesLayout.addWidget(self.mc_tm3)
        #Horario miercoles 4
        self.mc_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mc_tm4.setObjectName("mc_tm4")
        self.mc_tm4.clear()  
        self.mc_tm4.setSpecialValueText("--:--:--") 
        self.mc_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mc_tm4.setTime(QtCore.QTime())  
        self.MiercolesLayout.addWidget(self.mc_tm4)
        #Horario miercoles 5
        self.mc_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.mc_tm5.setObjectName("mc_tm5")
        self.mc_tm5.clear()  
        self.mc_tm5.setSpecialValueText("--:--:--")  
        self.mc_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.mc_tm5.setTime(QtCore.QTime())  
        self.MiercolesLayout.addWidget(self.mc_tm5)
        
        self.SemanaLayout.addLayout(self.MiercolesLayout) #añade cuadro miercoles al cuadro semana
        
        #Cuadro Jueves
        self.JuevesLayout = QtWidgets.QVBoxLayout()
        self.JuevesLayout.setObjectName("JuevesLayout")
        self.cartel_jueves = QtWidgets.QLabel(self.horizontalLayoutWidget) #Etiqueta jueves
        self.cartel_jueves.setObjectName("cartel_jueves")
        self.JuevesLayout.addWidget(self.cartel_jueves)
        #entrada limite jueves
        self.lm_jv = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_jv.setObjectName("lm_jv")
        self.lm_jv.clear()  
        self.lm_jv.setSpecialValueText("--")
        self.lm_jv.setMinimum(-1)
        self.lm_jv.setMaximum(10)
        self.lm_jv.setValue(-1)
        self.JuevesLayout.addWidget(self.lm_jv)
        #Horario jueves 1
        self.jv_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.jv_tm1.setObjectName("jv_tm1")
        self.jv_tm1.clear()  
        self.jv_tm1.setSpecialValueText("--:--:--")  
        self.jv_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.jv_tm1.setTime(QtCore.QTime())  
        self.JuevesLayout.addWidget(self.jv_tm1)
        #Horario jueves 2
        self.jv_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.jv_tm2.setObjectName("jv_tm2")
        self.jv_tm2.clear()  
        self.jv_tm2.setSpecialValueText("--:--:--")  
        self.jv_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.jv_tm2.setTime(QtCore.QTime()) 
        self.JuevesLayout.addWidget(self.jv_tm2)
        #Horario jueves 3
        self.jv_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.jv_tm3.setObjectName("jv_tm3")
        self.jv_tm3.clear()  
        self.jv_tm3.setSpecialValueText("--:--:--")  
        self.jv_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.jv_tm3.setTime(QtCore.QTime())  
        self.JuevesLayout.addWidget(self.jv_tm3)
        #Horario jueves 4
        self.jv_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.jv_tm4.setObjectName("jv_tm4")
        self.jv_tm4.clear()  
        self.jv_tm4.setSpecialValueText("--:--:--")  
        self.jv_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.jv_tm4.setTime(QtCore.QTime())  
        self.JuevesLayout.addWidget(self.jv_tm4)
        #Horario jueves 5
        self.jv_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.jv_tm5.setObjectName("jv_tm5")
        self.jv_tm5.clear()  
        self.jv_tm5.setSpecialValueText("--:--:--")  
        self.jv_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.jv_tm5.setTime(QtCore.QTime()) 
        self.JuevesLayout.addWidget(self.jv_tm5)
        
        self.SemanaLayout.addLayout(self.JuevesLayout) #añade el cuadro jueves al cuadro semana
        
        #Cuadro Viernes
        self.ViernesLayout = QtWidgets.QVBoxLayout()
        self.ViernesLayout.setObjectName("ViernesLayout")
        self.cartel_viernes = QtWidgets.QLabel(self.horizontalLayoutWidget) #Etiqueta viernes
        self.cartel_viernes.setObjectName("cartel_viernes")
        self.ViernesLayout.addWidget(self.cartel_viernes)
        #entrada limite viernes
        self.lm_vn = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_vn.setObjectName("lm_vn")
        self.lm_vn.clear()  
        self.lm_vn.setSpecialValueText("--")
        self.lm_vn.setMinimum(-1)
        self.lm_vn.setMaximum(10)
        self.lm_vn.setValue(-1)
        self.ViernesLayout.addWidget(self.lm_vn)
        #Horario viernes 1
        self.vn_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.vn_tm1.setObjectName("vn_tm1")
        self.vn_tm1.clear() 
        self.vn_tm1.setSpecialValueText("--:--:--")  
        self.vn_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59)) 
        self.vn_tm1.setTime(QtCore.QTime())  
        self.ViernesLayout.addWidget(self.vn_tm1)
        #Horario viernes 2
        self.vn_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.vn_tm2.setObjectName("vn_tm2")
        self.vn_tm2.clear()  
        self.vn_tm2.setSpecialValueText("--:--:--") 
        self.vn_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59)) 
        self.vn_tm2.setTime(QtCore.QTime())  
        self.ViernesLayout.addWidget(self.vn_tm2)
        #Horario viernes 3
        self.vn_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.vn_tm3.setObjectName("vn_tm3")
        self.vn_tm3.clear()  
        self.vn_tm3.setSpecialValueText("--:--:--")  
        self.vn_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.vn_tm3.setTime(QtCore.QTime())  
        self.ViernesLayout.addWidget(self.vn_tm3)
        #Horario viernes 4
        self.vn_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.vn_tm4.setObjectName("vn_tm4")
        self.vn_tm4.clear()  
        self.vn_tm4.setSpecialValueText("--:--:--")  
        self.vn_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.vn_tm4.setTime(QtCore.QTime())  
        self.ViernesLayout.addWidget(self.vn_tm4)
        #Horario viernes 5
        self.vn_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.vn_tm5.setObjectName("vn_tm5")
        self.vn_tm5.clear()  
        self.vn_tm5.setSpecialValueText("--:--:--")  
        self.vn_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.vn_tm5.setTime(QtCore.QTime())  
        self.ViernesLayout.addWidget(self.vn_tm5)
        
        self.SemanaLayout.addLayout(self.ViernesLayout) #añade cueadro viernes al cuadro semana
        
        #Cuadro Sabado
        self.SabadoLayout = QtWidgets.QVBoxLayout()
        self.SabadoLayout.setObjectName("SabadoLayout")
        self.cartel_sabado = QtWidgets.QLabel(self.horizontalLayoutWidget) #etiqueta sabado
        self.cartel_sabado.setObjectName("cartel_sabado")
        self.SabadoLayout.addWidget(self.cartel_sabado)
        #entrada limite sabado
        self.lm_sb = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_sb.setObjectName("lm_sb-")
        self.lm_sb.clear()  
        self.lm_sb.setSpecialValueText("--")
        self.lm_sb.setMinimum(-1)
        self.lm_sb.setMaximum(10)
        self.lm_sb.setValue(-1)
        self.SabadoLayout.addWidget(self.lm_sb)
        #Horario sabado 1
        self.sb_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.sb_tm1.setObjectName("sb_tm1")
        self.sb_tm1.clear()  
        self.sb_tm1.setSpecialValueText("--:--:--")  
        self.sb_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.sb_tm1.setTime(QtCore.QTime())  
        self.SabadoLayout.addWidget(self.sb_tm1)
        #Horario sabado 2
        self.sb_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.sb_tm2.setObjectName("sb_tm2")
        self.sb_tm2.clear()  
        self.sb_tm2.setSpecialValueText("--:--:--")  
        self.sb_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.sb_tm2.setTime(QtCore.QTime())  
        self.SabadoLayout.addWidget(self.sb_tm2)
        #Horario sabado 3
        self.sb_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.sb_tm3.setObjectName("sb_tm3")
        self.sb_tm3.clear()  
        self.sb_tm3.setSpecialValueText("--:--:--") 
        self.sb_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.sb_tm3.setTime(QtCore.QTime()) 
        self.SabadoLayout.addWidget(self.sb_tm3)
        #Horario sabado 4
        self.sb_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.sb_tm4.setObjectName("sb_tm4")
        self.sb_tm4.clear()  
        self.sb_tm4.setSpecialValueText("--:--:--")  
        self.sb_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.sb_tm4.setTime(QtCore.QTime())  
        self.SabadoLayout.addWidget(self.sb_tm4)
        #Horario sabado 5
        self.sb_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.sb_tm5.setObjectName("sb_tm5")
        self.sb_tm5.clear()  
        self.sb_tm5.setSpecialValueText("--:--:--")  
        self.sb_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.sb_tm5.setTime(QtCore.QTime())  
        self.SabadoLayout.addWidget(self.sb_tm5)
        
        self.SemanaLayout.addLayout(self.SabadoLayout) #añade cuadro viernes al cuadro semana
        
        #Cuadro Domingo
        self.DomingoLayout = QtWidgets.QVBoxLayout()
        self.DomingoLayout.setObjectName("DomingoLayout")
        self.cartel_domingo = QtWidgets.QLabel(self.horizontalLayoutWidget) #etiqueta domingo
        self.cartel_domingo.setObjectName("cartel_domingo")
        self.DomingoLayout.addWidget(self.cartel_domingo)
        #entrada limite domingo
        self.lm_dg = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.lm_dg.setObjectName("lm_dg")
        self.lm_dg.clear()  
        self.lm_dg.setSpecialValueText("--")
        self.lm_dg.setMinimum(-1)
        self.lm_dg.setMaximum(10)
        self.lm_dg.setValue(-1)
        self.DomingoLayout.addWidget(self.lm_dg)
        #Horario domingo 1
        self.dg_tm1 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.dg_tm1.setObjectName("dg_tm1")
        self.dg_tm1.clear()  
        self.dg_tm1.setSpecialValueText("--:--:--")  
        self.dg_tm1.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59)) 
        self.dg_tm1.setTime(QtCore.QTime())  
        self.DomingoLayout.addWidget(self.dg_tm1)
        #Horario domingo 2
        self.dg_tm2 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.dg_tm2.setObjectName("dg_tm2")
        self.dg_tm2.clear()  
        self.dg_tm2.setSpecialValueText("--:--:--") 
        self.dg_tm2.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.dg_tm2.setTime(QtCore.QTime())  
        self.DomingoLayout.addWidget(self.dg_tm2)
        #Horario domingo 3
        self.dg_tm3 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.dg_tm3.setObjectName("dg_tm3")
        self.dg_tm3.clear()  
        self.dg_tm3.setSpecialValueText("--:--:--")  
        self.dg_tm3.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59))  
        self.dg_tm3.setTime(QtCore.QTime())  
        self.DomingoLayout.addWidget(self.dg_tm3)
        #Horario domingo 4
        self.dg_tm4 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.dg_tm4.setObjectName("dg_tm4")
        self.dg_tm4.clear()  
        self.dg_tm4.setSpecialValueText("--:--:--")  
        self.dg_tm4.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59)) 
        self.dg_tm4.setTime(QtCore.QTime())  
        self.DomingoLayout.addWidget(self.dg_tm4)
        #Horario domingo 5
        self.dg_tm5 = QtWidgets.QTimeEdit(self.horizontalLayoutWidget)
        self.dg_tm5.setObjectName("dg_tm5")
        self.dg_tm5.clear()  
        self.dg_tm5.setSpecialValueText("--:--:--")  
        self.dg_tm5.setTimeRange(QtCore.QTime(0, 0, 0), QtCore.QTime(23, 59, 59)) 
        self.dg_tm5.setTime(QtCore.QTime())  
        self.DomingoLayout.addWidget(self.dg_tm5)
        
        self.SemanaLayout.addLayout(self.DomingoLayout) #añade cuadro Domingo al cuadro semana

        self.enviar_boton = QtWidgets.QPushButton(self.centralwidget)
        self.enviar_boton.setGeometry(QtCore.QRect(750, 238, 91, 30))
        self.enviar_boton.setObjectName("enviar_boton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.volver_boton.clicked.connect(MainWindow.show_menu) 
        self.enviar_boton.clicked.connect(MainWindow.enviar_dato) 
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.volver_boton.setText(_translate("MainWindow", "Volver"))
        self.cartel_general.setText(_translate("MainWindow", "General"))
        self.cartel_lunes.setText(_translate("MainWindow", "Lunes"))
        self.cartel_martes.setText(_translate("MainWindow", "Martes"))
        self.cartel_miercoles.setText(_translate("MainWindow", "Miercoles"))
        self.cartel_jueves.setText(_translate("MainWindow", "Jueves"))
        self.cartel_viernes.setText(_translate("MainWindow", "Viernes"))
        self.cartel_sabado.setText(_translate("MainWindow", "Sabado"))
        self.cartel_domingo.setText(_translate("MainWindow", "Domingo"))
        self.enviar_boton.setText(_translate("MainWindow", "Enviar"))

    
