# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 252)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.config_boton = QtWidgets.QPushButton(self.centralwidget)
        self.config_boton.setGeometry(QtCore.QRect(270, 40, 221, 71))
        self.config_boton.setObjectName("pushButton")
        self.estadistic_boton = QtWidgets.QPushButton(self.centralwidget)
        self.estadistic_boton.setGeometry(QtCore.QRect(270, 130, 221, 71))
        self.estadistic_boton.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 0, 71, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.config_boton.clicked.connect(MainWindow.show_config) # type: ignore
        self.estadistic_boton.clicked.connect(MainWindow.show_estadistic) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.config_boton.setText(_translate("MainWindow", "Configuración"))
        self.estadistic_boton.setText(_translate("MainWindow", "Estadísticas"))
        self.label.setText(_translate("MainWindow", "Bienvenido "))
