# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 940)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Fondo = QtWidgets.QFrame(self.centralwidget)
        self.Fondo.setStyleSheet("QFrame {\n"
"    background-image: url(../Graficos/1.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.Fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fondo.setObjectName("Fondo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Fondo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Estadisticas_frame = QtWidgets.QFrame(self.Fondo)
        self.Estadisticas_frame.setStyleSheet("QFrame {\n"
"    background: transparent;\n"
"}\n"
"")
        self.Estadisticas_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Estadisticas_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Estadisticas_frame.setObjectName("Estadisticas_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Estadisticas_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(347, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame_4 = QtWidgets.QFrame(self.Estadisticas_frame)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background: transparent;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.estadistic_boton = QtWidgets.QPushButton(self.frame_4)
        self.estadistic_boton.setEnabled(True)
        self.estadistic_boton.setGeometry(QtCore.QRect(40, 87, 655, 130))
        self.estadistic_boton.setStyleSheet("QPushButton {\n"
"    background-color: blue;  /* Cambia \'green\' al color que prefieras */\n"
"    color: white;  /* Cambia \'white\' al color del texto que prefieras */\n"
"border rad\n"
"}\n"
"QPushButton { border-radius: 60px; /* Ajusta el valor para hacer el botón más o menos redondeado / background-color: #3498db; / Color de fondo del botón / color: white; / Color del texto del botón / border: 12px solid #2980b9; / Borde del botón */ }")
        self.estadistic_boton.setObjectName("estadistic_boton")
        self.horizontalLayout_2.addWidget(self.frame_4)
        spacerItem2 = QtWidgets.QSpacerItem(247, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 25)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout.addWidget(self.Estadisticas_frame)
        self.Configuracion_frame = QtWidgets.QFrame(self.Fondo)
        self.Configuracion_frame.setStyleSheet("QFrame {\n"
"    background: transparent;\n"
"}\n"
"")
        self.Configuracion_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Configuracion_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Configuracion_frame.setObjectName("Configuracion_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Configuracion_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(381, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.frame_5 = QtWidgets.QFrame(self.Configuracion_frame)
        self.frame_5.setStyleSheet("QFrame {\n"
"    background: transparent;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.config_boton = QtWidgets.QPushButton(self.frame_5)
        self.config_boton.setGeometry(QtCore.QRect(50, 87, 650, 130))
        self.config_boton.setStyleSheet("QPushButton {\n"
"    background-color: blue;  /* Cambia \'green\' al color que prefieras */\n"
"    color: white;  /* Cambia \'white\' al color del texto que prefieras */\n"
"border rad\n"
"}\n"
"QPushButton { border-radius: 60px; /* Ajusta el valor para hacer el botón más o menos redondeado / background-color: #3498db; / Color de fondo del botón / color: white; / Color del texto del botón / border: 12px solid #2980b9; / Borde del botón */ }")
        self.config_boton.setObjectName("config_boton")
        self.horizontalLayout_3.addWidget(self.frame_5)
        spacerItem4 = QtWidgets.QSpacerItem(237, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3.setStretch(0, 10)
        self.horizontalLayout_3.setStretch(1, 25)
        self.horizontalLayout_3.setStretch(2, 10)
        self.verticalLayout.addWidget(self.Configuracion_frame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 2)
        self.horizontalLayout.addWidget(self.Fondo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.estadistic_boton.clicked.connect(MainWindow.show_estadistic) # type: ignore
        self.config_boton.clicked.connect(MainWindow.show_config) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.estadistic_boton.setText(_translate("MainWindow", "Estadísticas"))
        self.config_boton.setText(_translate("MainWindow", "Configuración"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
